Сделал кнопки
js-tasks-ru/htmlcss-20231027_nikita-yudin pull request #5
Opened 2023-11-06 21:52 UTC by yudin-nikita

Сделал кнопки, исправил ошибки + сделал БЭМ

2023-11-06 21:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 21:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-08 22:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-09 21:45 UTC, GSemikozov requested changes

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +h1 {
строки 1-14:

1) почему в файле стилей конкретного компонента описываем глобальные стили?
2) почему описываем другие, вспомогательные блоки?

это все либо выносится в нормалайз, либо (как в случае с вспомогательными стилями) - в отдельный файл стилей который нужен только на странице с примером верстки компонента

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
не хватает font-family + line-height

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px;
при таких паддингах высота кнопки не будет 48 как в макете

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: color 200ms ease-in-out;
лишнее

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_disabled {
.btn:disabled, класс не нужен

2023-11-09 21:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn-primary {
модификаторы пишутся через `_`

2023-11-11 22:13 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +h1 {
исправил

2023-11-11 22:15 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
font-family прописан в mаin.css
line-height прописал

2023-11-11 22:16 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +    padding: 15px;
добавил line-height, высоту кнопки проверил, теперь 48

2023-11-11 22:16 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +    transition: color 200ms ease-in-out;
исправил

2023-11-11 22:16 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +.btn_disabled {
исправил

2023-11-11 22:16 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +.btn-primary {
исправил

2023-11-12 13:47 UTC, GSemikozov requested changes

2023-11-12 13:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2023-11-25 21:11 UTC, yudin-nikita commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
исправил

2023-12-02 20:10 UTC, GSemikozov approved these changes

2023-12-02 20:10 UTC, merged